services:
    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV:-production}
            - APP_DEBUG=${APP_DEBUG:-false}
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
            MYSQL_DATABASE: ${DB_DATABASE:-dex}
            MYSQL_USER: ${DB_USER:-dex}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
        ports:
            - "${DB_HOST_PORT:-3306}:${DB_PORT:-3306}"
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
